/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SQL;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Libro extends javax.swing.JFrame {

    /**
     * Creates new form Libro
     */
    Conexion c = new Conexion();
    Menu menu;
    public Libro(Menu jMenu) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/resources/icon.png")).getImage());
        menu = jMenu;
         jButDesencriptar.setEnabled(false);
    }
    
    public void soloNumeros(java.awt.event.KeyEvent evt){
    char val = evt.getKeyChar();
        if(Character.isLetter(val)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(null, "Dato de entrada alfabético =  inválido");
        }
    }
    
    public void soloLetras(java.awt.event.KeyEvent evt){
    char val = evt.getKeyChar();
        if(Character.isDigit(val)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(null, "Dato de entrada numérico = inválido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButVerLibros = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextIDLibro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextTitulo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextISBN = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextEditorial = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextNumPag = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextIDAutor = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextLibro = new javax.swing.JTextArea();
        jButAggLibros = new javax.swing.JButton();
        jButMenu = new javax.swing.JButton();
        jButDesencriptar = new javax.swing.JButton();
        jRadioDesencriptado = new javax.swing.JRadioButton();
        jButEncriptar = new javax.swing.JButton();
        jRadioEncriptado = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libros");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Libros");

        jButVerLibros.setText("Ver Libros");
        jButVerLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerLibrosActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("IDLibro");

        jTextIDLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDLibroActionPerformed(evt);
            }
        });
        jTextIDLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextIDLibroKeyTyped(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Codigo");

        jTextCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCodigoKeyTyped(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Titulo");

        jTextTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTituloKeyTyped(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("ISBN");

        jTextISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextISBNKeyTyped(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Editorial");

        jTextEditorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextEditorialKeyTyped(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("NumPag");

        jTextNumPag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNumPagKeyTyped(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("IDAutor");

        jTextIDAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextIDAutorKeyTyped(evt);
            }
        });

        jTextLibro.setEditable(false);
        jTextLibro.setColumns(20);
        jTextLibro.setRows(5);
        jScrollPane6.setViewportView(jTextLibro);

        jButAggLibros.setText("Agregar Libros");
        jButAggLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAggLibrosActionPerformed(evt);
            }
        });

        jButMenu.setText("Menu");
        jButMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMenuActionPerformed(evt);
            }
        });

        jButDesencriptar.setText("Desencriptar");
        jButDesencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDesencriptarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioDesencriptado);
        jRadioDesencriptado.setSelected(true);
        jRadioDesencriptado.setText("Desencriptado");
        jRadioDesencriptado.setEnabled(false);

        jButEncriptar.setText("Encriptar");
        jButEncriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEncriptarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioEncriptado);
        jRadioEncriptado.setText("Encriptado");
        jRadioEncriptado.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextIDLibro)
                                    .addComponent(jTextTitulo)
                                    .addComponent(jTextIDAutor)
                                    .addComponent(jButVerLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jTextISBN)
                            .addComponent(jTextNumPag))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButAggLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jButEncriptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioEncriptado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioDesencriptado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButDesencriptar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButMenu)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButVerLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextIDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButAggLibros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(jTextNumPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextIDAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButEncriptar)
                            .addComponent(jButDesencriptar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioEncriptado)
                            .addComponent(jRadioDesencriptado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButMenu)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButVerLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerLibrosActionPerformed
        // TODO add your handling code here:
        String texto = "";
        try {
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca "
            + "Select * from Libro";
            c.resultado = c.sentencia.executeQuery(sql);
             if(jRadioEncriptado.isSelected()){
            while(c.resultado.next()){
                texto += "IDLibro = "+c.resultado.getString("IDLibro_Encrypted")
                +", Codigo = "+c.resultado.getInt("Codigo")
                +", Titulo = "+c.resultado.getString("Titulo")
                +", ISBN = "+c.resultado.getString("ISBN")
                +", Editorial = "+c.resultado.getString("Editorial")
                +", Numero de pagina = "+c.resultado.getInt("NumPag")
                +", ID Autor = "+c.resultado.getInt("IDAutor")+""
                +"\n";
            }
            }else if(jRadioDesencriptado.isSelected())
                  while(c.resultado.next()){
                texto += "ID Libro = " + c.resultado.getInt("IDLibro")
                +", Codigo = "+c.resultado.getInt("Codigo")
                +", Titulo = "+c.resultado.getString("Titulo")
                +", ISBN = "+c.resultado.getString("ISBN")
                +", Editorial = "+c.resultado.getString("Editorial")
                +", Numero de pagina = "+c.resultado.getInt("NumPag")
                +", ID Autor = "+c.resultado.getInt("IDAutor")+"\n";
              }
        }catch(SQLException ex){
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextLibro.setText(texto);

    }//GEN-LAST:event_jButVerLibrosActionPerformed

    private void jButAggLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAggLibrosActionPerformed
        // TODO add your handling code here:
        try{
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca "
            + "insert into Libro values("
            + jTextIDLibro.getText()+","
            + jTextCodigo.getText()+","
            +"'"+jTextTitulo.getText()+"',"
            +"'"+jTextISBN.getText()+"',"
            +"'"+jTextEditorial.getText()+"',"
            +jTextNumPag.getText()+","
            +jTextIDAutor.getText()+")";

            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(this, "El Libro se agregó correctamente");
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButVerLibros.doClick();
    }//GEN-LAST:event_jButAggLibrosActionPerformed

    private void jButMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMenuActionPerformed
        // TODO add your handling code here:
          this.dispose();
          menu.setVisible(true);
    }//GEN-LAST:event_jButMenuActionPerformed

    private void jButDesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDesencriptarActionPerformed
        // TODO add your handling code here:
        String texto = "";
        try{
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca "
            +"Select IDLibro, IDLibro_Encrypted AS 'ID Libro Encriptado', "
            +"CONVERT(int ,DECRYPTBYKEY(IDLibro_Encrypted,0, "
            +"HashBytes('SHA1',CONVERT(varbinary,IDAutor)))) "
            +"AS 'Decrypted ID Libro' from Libro";

            c.resultado = c.sentencia.executeQuery(sql);

            JOptionPane.showMessageDialog(this, "El ID del Libro se a desencriptado correctamente");
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButDesencriptar.setEnabled(false);
        jButEncriptar.setEnabled(true);
        jRadioDesencriptado.setSelected(true);
        jButVerLibros.doClick();
        
    }//GEN-LAST:event_jButDesencriptarActionPerformed

    private void jButEncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEncriptarActionPerformed
        // TODO add your handling code here:
        try{
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca "
            +"OPEN SYMMETRIC KEY MySymmetricKey "
            +"DECRYPTION BY CERTIFICATE MyCertificate; "
            +"Update Libro "
            +"Set IDLibro_Encrypted =  EncryptByKey(Key_GUID('MySymmetricKey'),CONVERT(varbinary, IDLibro));";

            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(this, "El ID del Libro se a encriptado correctamente");
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButDesencriptar.setEnabled(true);
        jButEncriptar.setEnabled(false);
        jRadioEncriptado.setSelected(true);
        jButVerLibros.doClick();
    }//GEN-LAST:event_jButEncriptarActionPerformed

    private void jTextIDLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDLibroActionPerformed

    private void jTextIDLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextIDLibroKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_jTextIDLibroKeyTyped

    private void jTextTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTituloKeyTyped
        // TODO add your handling code here:
        soloLetras(evt);
    }//GEN-LAST:event_jTextTituloKeyTyped

    private void jTextEditorialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEditorialKeyTyped
        // TODO add your handling code here:
        soloLetras(evt);
    }//GEN-LAST:event_jTextEditorialKeyTyped

    private void jTextIDAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextIDAutorKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_jTextIDAutorKeyTyped

    private void jTextCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCodigoKeyTyped
        // TODO add your handling code here
        soloNumeros(evt);
    }//GEN-LAST:event_jTextCodigoKeyTyped

    private void jTextISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextISBNKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_jTextISBNKeyTyped

    private void jTextNumPagKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNumPagKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_jTextNumPagKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libro(new Menu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButAggLibros;
    private javax.swing.JButton jButDesencriptar;
    private javax.swing.JButton jButEncriptar;
    private javax.swing.JButton jButMenu;
    private javax.swing.JButton jButVerLibros;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioDesencriptado;
    private javax.swing.JRadioButton jRadioEncriptado;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextEditorial;
    private javax.swing.JTextField jTextIDAutor;
    private javax.swing.JTextField jTextIDLibro;
    private javax.swing.JTextField jTextISBN;
    private javax.swing.JTextArea jTextLibro;
    private javax.swing.JTextField jTextNumPag;
    private javax.swing.JTextField jTextTitulo;
    // End of variables declaration//GEN-END:variables
}
