/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SQL;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Prestamos extends javax.swing.JFrame {

    /**
     * Creates new form Prestamos
     */
    Conexion c = new Conexion();
    Menu menu;
    public Prestamos(Menu jMenu) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/resources/icon.png")).getImage());
        menu = jMenu;
         jButDesencriptar.setEnabled(false);
    }
    public void soloNumeros(java.awt.event.KeyEvent evt){
    char val = evt.getKeyChar();
        if(Character.isLetter(val)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(null, "Dato de entrada alfabético =  inválido");
        }
    }
    
    public void soloLetras(java.awt.event.KeyEvent evt){
    char val = evt.getKeyChar();
        if(Character.isDigit(val)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(null, "Dato de entrada numérico = inválido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButVerPrestamos = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextPrestamosIDPrestamos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextPrestamosIDLibros = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextPrestamosIDUsuario = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextPrestamosFccPrestamo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextPrestamosFccDevolucion = new javax.swing.JTextField();
        jButAggPrestamos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPrestamos = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButVerPrestamos1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextIDPrestamos = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextIDLibros = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextIDUsuario = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFccPrestamo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFccDevolucion = new javax.swing.JTextField();
        jButAggPrestamos1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAPrestamos = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jRadioEncriptado = new javax.swing.JRadioButton();
        jButEncriptar = new javax.swing.JButton();
        jButDesencriptar = new javax.swing.JButton();
        jRadioDesencriptado = new javax.swing.JRadioButton();

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Prestamos");

        jButVerPrestamos.setText("Ver Prestamos");
        jButVerPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerPrestamosActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("IDPrestamo");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("IDLibro");

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("IDUsuario");

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Fecha prestamo y hora");

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Fecha Devolución y hora");

        jButAggPrestamos.setText("Agregar Prestamos");
        jButAggPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAggPrestamosActionPerformed(evt);
            }
        });

        jTextPrestamos.setEditable(false);
        jTextPrestamos.setColumns(20);
        jTextPrestamos.setRows(5);
        jScrollPane1.setViewportView(jTextPrestamos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Prestamos");

        jButVerPrestamos1.setText("Ver Prestamos");
        jButVerPrestamos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerPrestamos1ActionPerformed(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("IDPrestamo");

        jTextIDPrestamos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextIDPrestamosKeyTyped(evt);
            }
        });

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("IDLibro");

        jTextIDLibros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextIDLibrosKeyTyped(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("IDUsuario");

        jTextIDUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextIDUsuarioKeyTyped(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Fecha prestamo AAAA-MM-DD");

        jTextFccPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFccPrestamoKeyTyped(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Fecha Devolución AAAA-MM-DD");

        jTextFccDevolucion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFccDevolucionKeyTyped(evt);
            }
        });

        jButAggPrestamos1.setText("Agregar Prestamos");
        jButAggPrestamos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAggPrestamos1ActionPerformed(evt);
            }
        });

        jTextAPrestamos.setEditable(false);
        jTextAPrestamos.setColumns(20);
        jTextAPrestamos.setRows(5);
        jScrollPane2.setViewportView(jTextAPrestamos);

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioEncriptado);
        jRadioEncriptado.setText("Encriptado");
        jRadioEncriptado.setEnabled(false);

        jButEncriptar.setText("Encriptar");
        jButEncriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEncriptarActionPerformed(evt);
            }
        });

        jButDesencriptar.setText("Desencriptar");
        jButDesencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDesencriptarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioDesencriptado);
        jRadioDesencriptado.setSelected(true);
        jRadioDesencriptado.setText("Desencriptado");
        jRadioDesencriptado.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(5, 5, 5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButVerPrestamos1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFccDevolucion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                            .addComponent(jTextIDUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextIDPrestamos, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextIDLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                    .addComponent(jTextFccPrestamo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButAggPrestamos1))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jButEncriptar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                                    .addComponent(jRadioEncriptado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButDesencriptar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jRadioDesencriptado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButVerPrestamos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextIDPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jTextIDLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jTextFccPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButAggPrestamos1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButEncriptar)
                            .addComponent(jButDesencriptar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioEncriptado)
                            .addComponent(jRadioDesencriptado)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jTextFccDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButVerPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerPrestamosActionPerformed
        // TODO add your handling code here:
        String texto = "";
        try {
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca "
            + "Select * from Prestamos";
            c.resultado = c.sentencia.executeQuery(sql);
            while(c.resultado.next()){
                texto += "ID Prestamo = " + c.resultado.getInt("IDPrestamo")
                +", ID Libro = "+c.resultado.getInt("IDLibro")
                +", ID Usuario = "+c.resultado.getInt("IDUsuario")
                +", Fecha prestamo = "+c.resultado.getString("FccPrestamo")
                +", Fecha Devolución = "+c.resultado.getString("FccDevolucion")+"\n";
            }

        }catch(SQLException ex){
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextPrestamos.setText(texto);
    }//GEN-LAST:event_jButVerPrestamosActionPerformed

    private void jButAggPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAggPrestamosActionPerformed
        // TODO add your handling code here:
        try{
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca " +
            "insert into Prestamos values(" +
            jTextPrestamosIDPrestamos.getText()+","+
            jTextPrestamosIDLibros.getText()+","+
            jTextPrestamosIDUsuario.getText()+","+
            "convert(datetime,'"+jTextPrestamosFccPrestamo.getText()+"'),"+
            "convert(datetime,'"+jTextPrestamosFccDevolucion.getText()+"'))";

            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(this, "El Prestamo se agregó correctamente");
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButAggPrestamosActionPerformed

    private void jButVerPrestamos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerPrestamos1ActionPerformed
        // TODO add your handling code here:
        String texto = "";
        try {
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca "
            + "Select * from Prestamos";
            c.resultado = c.sentencia.executeQuery(sql);
            if(jRadioEncriptado.isSelected()){
            while(c.resultado.next()){
                texto +="ID Prestamo = "+c.resultado.getString("IDPrestamo_Encrypted")
                      +", ID Libro = "+c.resultado.getInt("IDLibro")
                      +", ID Usuario = "+c.resultado.getInt("IDUsuario")
                      +", Fecha prestamo = "+c.resultado.getString("FccPrestamo")
                      +", Fecha Devolución = "+c.resultado.getString("FccDevolucion")
                      +"\n";
            }
            }else
                 while(c.resultado.next()){
                texto += "ID Prestamo = " + c.resultado.getInt("IDPrestamo")
                +", ID Libro = "+c.resultado.getInt("IDLibro")
                +", ID Usuario = "+c.resultado.getInt("IDUsuario")
                +", Fecha prestamo = "+c.resultado.getString("FccPrestamo")
                +", Fecha Devolución = "+c.resultado.getString("FccDevolucion")+"\n";
                 }
        }catch(SQLException ex){
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextAPrestamos.setText(texto);
    }//GEN-LAST:event_jButVerPrestamos1ActionPerformed

    private void jButAggPrestamos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAggPrestamos1ActionPerformed
        // TODO add your handling code here:
        try{
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca " +
            "insert into Prestamos values(" +
            jTextIDPrestamos.getText()+","+
            jTextIDLibros.getText()+","+
            jTextIDUsuario.getText()+","+
            "convert(datetime,"+jTextFccPrestamo.getText()+"),"+
            "convert(datetime,"+jTextFccDevolucion.getText()+"), null)";

            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(this, "El Prestamo se agregó correctamente");
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButVerPrestamos1.doClick();
    }//GEN-LAST:event_jButAggPrestamos1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButEncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEncriptarActionPerformed
        // TODO add your handling code here:
        try{
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca "
            +"OPEN SYMMETRIC KEY MySymmetricKey "
            +"DECRYPTION BY CERTIFICATE MyCertificate; "
            +"Update Prestamos "
            +"Set IDPrestamo_Encrypted = EncryptByKey(Key_GUID('MySymmetricKey'),CONVERT(varbinary, IDPrestamo));";

            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(this, "El ID del Prestamo se a encriptado correctamente");
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButDesencriptar.setEnabled(true);
        jButEncriptar.setEnabled(false);
        jRadioEncriptado.setSelected(true);
        jButVerPrestamos1.doClick();
    }//GEN-LAST:event_jButEncriptarActionPerformed

    private void jButDesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDesencriptarActionPerformed
        // TODO add your handling code here:
        String texto = "";
        try{
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca "
            +"Select IDPrestamo, IDPrestamo_Encrypted AS 'ID Prestamo Encriptado', "
            +"CONVERT(int ,DECRYPTBYKEY(IDPrestamo_Encrypted,0, "
            +"HashBytes('SHA1',CONVERT(varbinary,IDPrestamo))))  "
            +"AS 'Decrypted ID Prestamo' from Prestamos";

            c.resultado = c.sentencia.executeQuery(sql);

            JOptionPane.showMessageDialog(this, "El ID del Libro se a desencriptado correctamente");
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButDesencriptar.setEnabled(false);
        jButEncriptar.setEnabled(true);
        jRadioDesencriptado.setSelected(true);
        jButVerPrestamos1.doClick();

    }//GEN-LAST:event_jButDesencriptarActionPerformed

    private void jTextIDPrestamosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextIDPrestamosKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_jTextIDPrestamosKeyTyped

    private void jTextIDUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextIDUsuarioKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_jTextIDUsuarioKeyTyped

    private void jTextFccDevolucionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFccDevolucionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFccDevolucionKeyTyped

    private void jTextIDLibrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextIDLibrosKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_jTextIDLibrosKeyTyped

    private void jTextFccPrestamoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFccPrestamoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFccPrestamoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos(new Menu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButAggPrestamos;
    private javax.swing.JButton jButAggPrestamos1;
    private javax.swing.JButton jButDesencriptar;
    private javax.swing.JButton jButEncriptar;
    private javax.swing.JButton jButVerPrestamos;
    private javax.swing.JButton jButVerPrestamos1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioDesencriptado;
    private javax.swing.JRadioButton jRadioEncriptado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAPrestamos;
    private javax.swing.JTextField jTextFccDevolucion;
    private javax.swing.JTextField jTextFccPrestamo;
    private javax.swing.JTextField jTextIDLibros;
    private javax.swing.JTextField jTextIDPrestamos;
    private javax.swing.JTextField jTextIDUsuario;
    private javax.swing.JTextArea jTextPrestamos;
    private javax.swing.JTextField jTextPrestamosFccDevolucion;
    private javax.swing.JTextField jTextPrestamosFccPrestamo;
    private javax.swing.JTextField jTextPrestamosIDLibros;
    private javax.swing.JTextField jTextPrestamosIDPrestamos;
    private javax.swing.JTextField jTextPrestamosIDUsuario;
    // End of variables declaration//GEN-END:variables
}
