/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SQL;

import com.sun.org.apache.bcel.internal.generic.Select;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Biblioteca
     */
    Conexion c = new Conexion();
    Menu menu;
    public Usuarios(Menu jMenu) {
        initComponents();
                setIconImage(new ImageIcon(getClass().getResource("/resources/icon.png")).getImage());
                menu = jMenu;
                jButDesencriptar.setEnabled(false);
    }
    public void soloNumeros(java.awt.event.KeyEvent evt){
    char val = evt.getKeyChar();
        if(Character.isLetter(val)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(null, "Dato de entrada alfabético =  inválido");
        }
    }
    
    public void soloLetras(java.awt.event.KeyEvent evt){
    char val = evt.getKeyChar();
        if(Character.isDigit(val)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(null, "Dato de entrada numérico = inválido");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButVerUsuarios = new javax.swing.JButton();
        jButAggUsuarios = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextIDUsuario = new javax.swing.JTextField();
        jTextNumUsuario = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextNIF = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextUsuario = new javax.swing.JTextArea();
        jButMenu = new javax.swing.JButton();
        jRadioEncriptado = new javax.swing.JRadioButton();
        jButEncriptar = new javax.swing.JButton();
        jButDesencriptar = new javax.swing.JButton();
        jRadioDesencriptado = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Usuarios");

        jButVerUsuarios.setText("Ver Usuarios");
        jButVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerUsuariosActionPerformed(evt);
            }
        });

        jButAggUsuarios.setText("Agregar Usuarios");
        jButAggUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAggUsuariosActionPerformed(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("IDUsuario");

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Num Usuario");

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("DNI");

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Nombre");

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Dirección");

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Telefono");

        jTextIDUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextIDUsuarioKeyTyped(evt);
            }
        });

        jTextNumUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNumUsuarioKeyTyped(evt);
            }
        });

        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });

        jTextNIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNIFKeyTyped(evt);
            }
        });

        jTextTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTelefonoKeyTyped(evt);
            }
        });

        jTextUsuario.setEditable(false);
        jTextUsuario.setColumns(20);
        jTextUsuario.setRows(5);
        jScrollPane2.setViewportView(jTextUsuario);

        jButMenu.setText("Menu");
        jButMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMenuActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioEncriptado);
        jRadioEncriptado.setText("Encriptado");
        jRadioEncriptado.setEnabled(false);

        jButEncriptar.setText("Encriptar");
        jButEncriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEncriptarActionPerformed(evt);
            }
        });

        jButDesencriptar.setText("Desencriptar");
        jButDesencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDesencriptarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioDesencriptado);
        jRadioDesencriptado.setSelected(true);
        jRadioDesencriptado.setText("Desencriptado");
        jRadioDesencriptado.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButMenu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButVerUsuarios))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextNIF, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(jTextIDUsuario))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNumUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButAggUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jRadioEncriptado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButEncriptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButDesencriptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioDesencriptado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButVerUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jTextNumUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButAggUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButMenu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButEncriptar)
                            .addComponent(jButDesencriptar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioEncriptado)
                            .addComponent(jRadioDesencriptado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerUsuariosActionPerformed
        // TODO add your handling code here:
        String texto = "";
        try {
        c.ConectarBasedeDatos("");
        String sql = "use Biblioteca "
                + "Select * from Usuario";
        c.resultado = c.sentencia.executeQuery(sql);
        if(jRadioEncriptado.isSelected()){
        while(c.resultado.next()){
        texto +="ID Usuario= " + c.resultado.getString("IDUsuario_Encrypted")
                +", Numero Usuario = "+c.resultado.getInt("NumUsuario")
                +", DNI = "+c.resultado.getString("NIF")
                +", Nombre = "+c.resultado.getString("Nombre")
                +", Dirección = "+c.resultado.getString("Direccion")
                +", Telefono = "+c.resultado.getString("Telefono")
                +"\n";
        }
        }else 
        while(c.resultado.next()){
        texto += "ID Usuario= " + c.resultado.getInt("IDUsuario")
                +", Numero Usuario = "+c.resultado.getInt("NumUsuario")
                +", DNI = "+c.resultado.getString("NIF")
                +", Nombre = "+c.resultado.getString("Nombre")
                +", Dirección = "+c.resultado.getString("Direccion")
                +", Telefono = "+c.resultado.getString("Telefono")+"\n";
        }

        }catch(SQLException ex){
        Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextUsuario.setText(texto);
    }//GEN-LAST:event_jButVerUsuariosActionPerformed

    private void jButAggUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAggUsuariosActionPerformed
        // TODO add your handling code here:
         try{
        c.ConectarBasedeDatos("");
        String sql = "use Biblioteca " +
        "insert into Usuario values("+
        jTextIDUsuario.getText()+","+
        jTextNumUsuario.getText()+","+   
        jTextNIF.getText()+","+
        "'"+jTextNombre.getText()+"',"+
        "'"+jTextDireccion.getText()+"',"+
        "'"+jTextTelefono.getText()+"')";
        
        c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(this, "El Prestamo se agregó correctamente");
        c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButVerUsuarios.doClick();
    }//GEN-LAST:event_jButAggUsuariosActionPerformed

    private void jButMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_jButMenuActionPerformed

    private void jButEncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEncriptarActionPerformed
        // TODO add your handling code here:
        try{
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca "
            +"OPEN SYMMETRIC KEY MySymmetricKey "
            +"DECRYPTION BY CERTIFICATE MyCertificate; "
            +"Update Usuario "
            +"Set IDUsuario_Encrypted = EncryptByKey(Key_GUID('MySymmetricKey'),CONVERT(varbinary, IDUsuario));";

            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(this, "El ID del Usuario se a encriptado correctamente");
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButDesencriptar.setEnabled(true);
        jButEncriptar.setEnabled(false);
        jRadioEncriptado.setSelected(true);
        jButVerUsuarios.doClick();
    }//GEN-LAST:event_jButEncriptarActionPerformed

    private void jButDesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDesencriptarActionPerformed
        // TODO add your handling code here:
        String texto = "";
        try{
            c.ConectarBasedeDatos("");
            String sql = "use Biblioteca "
            +"Select IDUsuario, IDUsuario_Encrypted AS 'ID Usuario Encriptado',"
            +"CONVERT(int ,DECRYPTBYKEY(IDUsuario_Encrypted,0, "
            +"HashBytes('SHA1',CONVERT(varbinary,IDUsuario)))) "
            +"AS 'Decrypted ID Usuario' from Usuario";

            c.resultado = c.sentencia.executeQuery(sql);

            JOptionPane.showMessageDialog(this, "El ID del Libro se a desencriptado correctamente");
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButDesencriptar.setEnabled(false);
        jButEncriptar.setEnabled(true);
        jRadioDesencriptado.setSelected(true);
        jButVerUsuarios.doClick();
    }//GEN-LAST:event_jButDesencriptarActionPerformed

    private void jTextIDUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextIDUsuarioKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_jTextIDUsuarioKeyTyped

    private void jTextNIFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNIFKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_jTextNIFKeyTyped

    private void jTextNumUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNumUsuarioKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_jTextNumUsuarioKeyTyped

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        // TODO add your handling code here:
        soloLetras(evt);
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void jTextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelefonoKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_jTextTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios(new Menu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButAggUsuarios;
    private javax.swing.JButton jButDesencriptar;
    private javax.swing.JButton jButEncriptar;
    private javax.swing.JButton jButMenu;
    private javax.swing.JButton jButVerUsuarios;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioDesencriptado;
    private javax.swing.JRadioButton jRadioEncriptado;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextIDUsuario;
    private javax.swing.JTextField jTextNIF;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNumUsuario;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JTextArea jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
